---
- name: "Update templates"
  template:
    src:  "{{ item.src | default((item.dest | basename ()) + '.j2')}}"
    dest: "{{ item.dest }}"
  with_items:
    - dest: "/etc/profile.d/kubectl-bash-completion.sh"
    - dest: "/etc/profile.d/kubectl-kubeconfig.sh"
  when:
    - "kubectl is defined"
  tags:
    - "kubectl"
